server:
  port: 8081

spring:
  application:
    name: biography-course
  datasource:
    url: jdbc:mysql://localhost:3308/messagedb
    username: root
    password: messagedb

  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: none
    show-sql: true

  flyway:
    locations:
      classpath: db/migration

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    exchenge:
      producer: ex.producer.rabbitmq
    routing-key:
      producer: rk.producer.rabbitmq
    dead-letter:
      producer: dl.producer.aula-spring

