
CREATE TABLE message (
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    text VARCHAR(200) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);